name: Generate and Store Plot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pandas matplotlib

      - name: Generate Plot
        run: python scripts/generate_plot.py

      - name: Debugging Print current working directory
        run: pwd

      - name: Debugging List files in the current directory
        run: ls

      - name: Move Plot to Plots Directory
        run: mv generated_plot.png plots/

      - name: Debugging Print data content
        run: cat data/data.csv

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT }}
          branch: main

         
